restcontrollers:
    resource: ../../src/Controller/Rest/
    type: attribute
    prefix: /api

controllers:
    resource: ../../src/Controller/Admin/
    type: attribute

kernel:
    resource: ../../src/Kernel.php
    type: attribute
